version: "3.9"
services:
    poe-kafka-producer:
        build: .
        ports:
            - "3000:3000"
        links:
            - kafka:kafka
    kafka:
        image: spotify/kafka
        ports:
            - "2181:2181"
            - "9092:9092"
        environment:
            ADVERTISED_HOST: host.docker.internal
            ADVERTISED_PORT: 9092
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock